---
- hosts: app
  become: yes
  remote_user: vagrant

  vars_files:
    - vars.yaml

  pre_tasks:
    - name: Update cache if neccessary.
      apt: update_cache=yes cache_valid_time=3600

  handlers:
    - name: restart apache
      service: name=apache2 state=restarted

  tasks:
    - name: Get software for apt repository management.
      apt:
        state: present
        name:
          - python3-apt
          - python3-pycurl

    # - name: Add ondrej repository for later versions of PHP.
    #   deb822_repository: repo='ppa:ondrej/php' update_cache=yes

    - name: "Install Apache, MySQL, PHP, and other dependencies."
      apt:
        state: present
        name:
          - acl
          - git
          - curl
          - unzip
          - sendmail
          - apache2
          - php-common
          - php-cli
          - php-dev
          - php-gd
          - php-curl
          - php-opcache
          - php-xml
          - php-mbstring
          - php-pdo
          - php-mysql
          - php-apcu
          - libpcre2-dev
          - libapache2-mod-php
          - python3-mysqldb
          - mariadb-server

    - name: "Start Apache, Mysql and PHP"
      service: "name={{ item }} state=started enabled=yes"
      with_items:
        - apache2
        - mysql

    # Configure Apache
    - name: Enable Apache rewrite module.
      apache2_module: name=rewrite state=present
      notify: restart apache

    - name: Add Apache virtualhost for drupal.
      template:
        src: "templates/drupal.test.conf.j2"
        dest: "/etc/apache2/sites-available/{{ domain }}.test.conf"
        owner: root
        group: root
        mode: 0644
      notify: restart apache

    - name: Enable the drupal site
      command: >
        a2ensite {{ domain }}.test

        creates=/etc/apache2/sites-enabled/{{ domain }}.test.conf
      notify: restart apache   

    - name: Disable the default site
      command: >
        a2dissite 000-default
        removes=/etc/apache2/sites-enabled/000-default.conf
      notify: restart apache 

    # Configure PHP with lineinfile
    - name: Adjust OpCache memory.
      lineinfile:
        dest: "/etc/php/8.2/apache2/conf.d/10-opcache.ini"
        regexp: "^opcache.memory_consumption"
        line: "opcache.memory_consumption = 96"
        state: present
      notify: restart apache

    # Configure Mysql
    - name: Create a MySQL database for Drupal
      mysql_db: "db={{ domain }} state=present"

    
    - name: Create a MySQL user for drupal
      mysql_user:
        name: "{{ domain }}"
        password: "1234"
        priv: "{{ domain }}.*:ALL"
        host: localhost
        state: present

    # Download and install Composer
    - name: Download Composer installer
      get_url: 
        url: https://getcomposer.org/installer
        dest: /tmp/composer-installer.php
        mode: 0755

    - name: Run Composer installer
      command: >
        php composer-installer.php
        chdir=/tmp
        creates=/usr/local/bin/composer

    - name: Move composer into globally-accessible location
      command: >
        mv /tmp/composer.phar /usr/local/bin/composer
        creates=/usr/local/bin/composer

    # Create a Drupal project with Composer
    - name: Ensure Drupal directory exists
      file:
        path: "{{ drupal_core_path }}"
        state: directory
        owner: www-data 
        group: www-data 

    - name: Check if Drupal project already exists
      stat:
        path: "{{ drupal_core_path }}/composer.json"
      register: drupal_composer_json

    - name: Create Drupal project
      composer:
        command: create-project
        arguments: drupal/recommended-project "{{ drupal_core_path }}"
        working_dir: "{{ drupal_core_path }}"
        no_dev: true
      become_user: www-data
      when: not drupal_composer_json.stat.exists

    # Install Drupal with Drush
    - name: Add drush to the Drupal site with Composer
      composer:
        command: require
        arguments: drush/drush:11.*
        working_dir: "{{ drupal_core_path }}"
      become_user: www-data
      when: not drupal_composer_json.stat.exists

    - name: Install Drupal
      command: >
        vendor/bin/drush si -y --site-name="{{ drupal_site_name }}"
        --account-name=admin
        --account-pass=admin
        --db-url=mysql://{{ domain }}:1234@localhost/{{ domain }}
        --root={{ drupal_core_path }}/web
        chdir={{ drupal_core_path }}
        creates={{ drupal_core_path }}/web/sites/default/settings.php
      notify: restart apache
      become_user: www-data